services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: '${DB_PASSWORD:-StrongPassword1}'
      MSSQL_USER: 'mssql'
    ports:
      - '${DB_PORT:-1433}:1433'
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test:
        [
          'CMD',
          '/opt/mssql-tools/bin/sqlcmd',
          '-S',
          'localhost',
          '-U',
          '${DB_USER:-sa}',
          '-P',
          '${DB_PASSWORD:-StrongPassword1}',
          '-Q',
          'SELECT 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 30

  web:
    image: eviction-mediation-web-development
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    working_dir: /rails
    volumes:
      - .:/rails
    ports:
      - '${WEB_PORT:-3000}:3000'
    depends_on:
      db:
        condition: service_healthy
      mailpit:
        condition: service_started
      chrome:
        condition: service_started
    environment:
      RAILS_ENV: development
      DB_ADAPTER: sqlserver
      DB_HOST: ${DB_SERVICE:-db}
      DB_PORT: ${DB_PORT:-1433}
      DB_USERNAME: ${DB_USER:-sa}
      DB_PASSWORD: ${DB_PASSWORD:-StrongPassword1}
      MAILPIT_HOST: ${MAILPIT_HOST:-mailpit}
      MAILPIT_PORT: ${MAILPIT_SMTP_PORT:-1025}
      APP_URL: ${APP_URL:-localhost}:${WEB_PORT:-3000}
      APP_PROTOCOL: ${APP_PROTOCOL:-http}
      SELENIUM_REMOTE_URL: http://chrome:4444

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - '${MAILPIT_WEB_PORT:-8025}:8025'  # Web UI
      - '${MAILPIT_SMTP_PORT:-1025}:1025' # SMTP server
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    ports:
      - '4444:4444'
      - '7900:7900'
    environment:
      SE_NODE_MAX_SESSIONS: 5
      SE_NODE_SESSION_TIMEOUT: 150
      SE_VNC_NO_PASSWORD: 1

volumes:
  sqlserver_data:
